"""Add tracking fields to CustomerVisit

Revision ID: b59ff78099cf
Revises: c18f9263e3e3
Create Date: 2026-10-08 19:50:35.933693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59ff78099cf'
down_revision: Union[str, Sequence[str], None] = 'c18f9263e3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_visits', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('customer_visits', sa.Column('check_in_latitude', sa.Float(), nullable=True))
    op.add_column('customer_visits', sa.Column('check_in_longitude', sa.Float(), nullable=True))
    op.add_column('customer_visits', sa.Column('check_out_latitude', sa.Float(), nullable=True))
    op.add_column('customer_visits', sa.Column('check_out_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_visits', 'check_out_longitude')
    op.drop_column('customer_visits', 'check_out_latitude')
    op.drop_column('customer_visits', 'check_in_longitude')
    op.drop_column('customer_visits', 'check_in_latitude')
    op.drop_column('customer_visits', 'status')
    # ### end Alembic commands ###
