"""Add employee_id to Meeting

Revision ID: c18f9263e3e3
Revises: cdc30b687121
Create Date: 2026-10-08 19:46:06.967797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18f9263e3e3'
down_revision: Union[str, Sequence[str], None] = 'cdc30b687121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'employee_id')
    # ### end Alembic commands ###
